                // ---- Bot Pool (70 usernames) ----
                const BOT_POOL = [
                    'xX_N0sc0pe_Xx','GamerGod99','PixelProwler','NiggaOvulationMaster67','CockSucker4000',
                    'VoidWalker','NeonFrost','TurboSnipr','ByteMe','GoonHugger',
                    'StarForge','SkullCrushr','LazerBeamzz','ShadowReapr','EpstiensYachtCrew',
                    'QuantumBolt','IronClad77','ChaoticAnalGiver','FrostyBalls','MadFucker',
                    'EchoStrike','PhantomKey','DarkMatter9','OmegaForce','SilentBaiter',
                    'CyberNigga','ThunderFister','ArcLancer','VenomCoil','GoonRunner',
                    'SolarFlare','CosmicCummer','AustrianPainter','DeepFreeze','Hyperbaiter',
                    'RocketPunch','StaticCockSucker','AbyssalOne','CrystalEdge','NoobNiggle',
                    'LegendKiller','xXjewXx','SweatyBalls','ProGamer420','BallzInCousinsMouth',
                    'AimlessOne','LankanLipLicker','DingalingGod','FrameDroppr','BustingOnPussy',
                    'ReplayKing','BotDetector','SkillIssue','TryHardMode','GayGoy',
                    'GigaChad_IRL','WifePookiee','NoChill99','TouchGrass','ToxicDick',
                    'SaltShaker','RagequitR','TouchdownKid','DeltaOps','AutisticAlpha',
                    'ballsnigger','ZeroTwo_','LostSoul99','RatioPoster','OpiumHeavy',
                    "ShadowNigga", "RNG_God", "NoobSlayer99", "LuckyDuck", "LuckyFuck", 
                    "bumcracker67", "naperiggerson", "EFN", "ERN", "diddysbumhole", 
                    "wemby'slittletwink", "CP_WATCHER", "Ray_Piste", "Peter_File", 
                    "MrCoolJr", "MrCoolSr", "Drake's_Fat_Dick", "gothmommycracker", 
                    "NiggaBeater", "WSpeed_Editz", "ILoveMinors",  "StrongestIsraeliSoldier", 
                    "IDF_bootlicker", "Big_Yahu", "Jewish_City_Boy",
                    "i_have_scat_fetish", "piss_drinking_4ever", "sweatyArmpitLicker", 
                    "I_touch_boys", "GreenNiggaGreen", "buttholelicker", "i_love_littleGirls", 
                    "4yo_fucker", "PencilUpMyUrethra", "i_love_buttholes", "NiggaPooper4000", 
                    "67buttplugs_up_my_ass", "Liggy", "swerxl", "i_eat_poop", "PissDrinker67", 
                    "67_aura_buttkisser", "NIGGERNIGGERNIGGER", "epstien's_returning_customer", 
                    "ISpent67MilOnPornhub", "Child_Pornographer", "touchingLittleBoysRN", 
                    "littleGirls_littlePussy", "leniggler", "iPegBoys", "StrapOnDildo", 
                    "BiggestButtplug", "CornyMasterBaiter67", "bigbrolignezh", "iranianjew", 
                    "fuckdonaldotrumpo", "niggaToucher", "StinkyDihCheese", "xxxlButtPlugWearer", 
                    "TrollingRapist", "CSAM_lover", "IJerkToNTR", "Donald_Plump", 
                    "Hitler'sGoodLittleJew", "privateIslandOwner", "The_Big_Stien", 
                    "einstien'sIsland", "KKKforever", "BlackJew", "gayBBCsex", "IHateNiggers", 
                    "fuck_israelian_jews", "dihSucker4000", "neggernagger", "Jewish4skinEater",
                    "niggaGay", "racialSlurs4ever", "FaggotFetishFun", "gayNiggaFag", 
                    "gayNiggaButtplug", "MonsterDildoRider", "sexInPublic", "kindergartenRapist", 
                    "anal_sex", "funnyJew", "goldDigger_faggotNigger", "suck_dih_for_1$", 
                    "ProficientProstitute", "AdeptAtAnal", "ExpertElfFucker", "RetardedRapist", 
                    "67Nigger67", "XxxNIGGER420xxX", "BoyToucher", "epstien>einstien", "leBoobies", 
                    "bumbumSlapper", "BlissfulBlowjobs", "RavagingRimjobber", "lemme_eyp", "i_am_Jewish"
                ];

                // ---- Ambient Messages ----
                const AMBIENT = [
                    "just found a game on here that actually goes crazy",
                    "how long has this platform been around??",
                    "bro i've been scrolling for an hour and still finding new ones",
                    "the variety on here is actually insane",
                    "whoever is making these games needs a raise",
                    "okay i did NOT expect to be this entertained rn",
                    "found my new addiction ngl",
                    "this is what the internet was made for",
                    "i keep sending these to my friends",
                    "genuinely shocked how good some of these are",
                    "who made this one?? it's actually clean",
                    "my productivity is cooked. fully cooked.",
                    "okay that one was not it but the next one was 🔥",
                    "the range on here is wild. went from chill puzzle to full chaos",
                    "why is this platform so slept on",
                    "i need more people to know about this",
                    "literally said 5 more minutes 45 minutes ago",
                    "the way i just lost track of time completely",
                    "some of these are rough and some are genuinely brilliant",
                    "stumbled onto this site and now it's midnight",
                    "this scratches a very specific itch",
                    "no download, no install, just vibes",
                    "different game every time i scroll, this is dangerous",
                    "okay the curation on here is actually good",
                    "some of these games are clearly passion projects and it shows",
                    "found a hidden gem just now. not telling which one 😈",
                    "i love that these are all so different from each other",
                    "anyone else just bouncing between games for hours",
                    "new personal favourite just dropped in my feed",
                    "the fact that this is free is criminal",
                    "okay that was unexpected in the best way",
                    "ngl my standards for browser games just went up",
                    "this is the good part of the internet",
                    "i was bored for like 2 seconds and now i'm here",
                    "no ads no nonsense just games, love that",
                    "someone on here really said let me just make something cool",
                    "the creativity on this platform is unreal",
                    "i've recommended this to like 5 people today",
                    "okay i'm hooked. not even gonna pretend otherwise",
                    "different game, same addiction 💀",
                    "why does every game on here make me say 'one more go'",
                    "can't believe i haven't heard of this place before",
                    "going through these like episodes of a show",
                    "some of these games have no right being this polished",
                    "this is my third hour. i accept my fate.",
                    "just vibing honestly",
                    "the scroll never ends and i don't want it to",
                    "alright i need to tell someone: that last one was fire",
                    "genuinely don't know which is my favourite anymore",
                    "this platform is dangerous for anyone with free time 💀",
                    "why do jews control the weather",
                    "my sister got pregnant by a nigger again",
                    "i hate women so much it's unreal",
                    "all asians look like they smell like fish",
                    "just caught my dad sucking off the mailman",
                    "kys you dirty sandnigger",
                    "why are black people allowed to exist",
                    "my mom is such a massive whore",
                    "jews did 9/11 and my dad",
                    "i want to fuck my cousin so bad",
                    "trannies should all be put in camps",
                    "indians smell like shit and failure",
                    "i hope israel gets glassed",
                    "my girlfriend left me for a chink",
                    "women belong in the kitchen getting beaten",
                    "blacks have smaller brains than my dog",
                    "i jerked off to my sister yesterday",
                    "fuck jews fuck israel fuck netanyahu",
                    "mexicans are literally cockroaches",
                    "i wish hitler finished the job",
                    "my dad beats me but at least hes not gay",
                    "all feminists deserve to be raped",
                    "chinese people eat their own babies",
                    "i hate faggots more than i hate life",
                    "why wont my mom let me fuck her",
                    "jews ruined my ranked games again",
                    "arabs fuck goats and then their sisters",
                    "i hope every nigger dies in a fire",
                    "my ex is a dirty jew whore",
                    "white women are all cum dumpsters",
                    "pakis are the worst kind of brown",
                    "i lost again because of the fucking jews",
                    "trannies make me want to commit war crimes",
                    "my uncle touched me but he was hungarian",
                    "women shouldnt be allowed to speak",
                    "blacks smell like welfare and crime",
                    "i want to bomb a pride parade",
                    "jews stole my foreskin and my happiness",
                    "koreans are just autistic chinks",
                    "i fuck my pillow and pretend its my cousin",
                    "all muslims should be deported to hell",
                    "my sister has onlyfans and im subscribed",
                    "hitler was right about everything",
                    "why are indians so fucking greasy",
                    "i blame israel for my small dick",
                    "niggers ruin everything they touch",
                    "i hope your mom gets fucked by niggers",
                    "feminists are just ugly whores with daddy issues",
                    "the idf killed my vibe again",
                    "i lost this game because netanyahu rigged it",
                ];

                // ---- Scripted Conversations (multi-turn) ----
                const CONVOS = [
                    [
                        { bot: 0, text: "how do you even find out about this site" },
                        { bot: 1, text: "a friend sent me a link like a week ago" },
                        { bot: 0, text: "bro same. zero marketing yet somehow everyone's here" },
                        { bot: 1, text: "word of mouth goes crazy apparently" },
                    ],
                    [
                        { bot: 2, text: "okay which game do i start with" },
                        { bot: 3, text: "just scroll and whatever catches your eye" },
                        { bot: 2, text: "that's not helpful lol" },
                        { bot: 3, text: "it genuinely is though, trust the feed" },
                    ],
                    [
                        { bot: 1, text: "does anyone know who's actually building all these" },
                        { bot: 4, text: "the simga himself" },
                        { bot: 1, text: "who is that" },
                        { bot: 4, text: "the goat" },
                        { bot: 1, text: "alright thanks bro" },
                    ],
                    [
                        { bot: 0, text: "i went from a chill puzzle to a full on chaos game in like 10 minutes" },
                        { bot: 2, text: "that's just the experience here lol" },
                        { bot: 0, text: "i love it and i hate it" },
                        { bot: 2, text: "yeah that's the correct reaction" },
                    ],
                    [
                        { bot: 3, text: "anyone else just not go back to their old games after finding this" },
                        { bot: 1, text: "my steam library hasn't been opened in weeks" },
                        { bot: 3, text: "exactly. why boot up a whole launcher" },
                        { bot: 4, text: "and yet the quality here is actually crazy" },
                    ],
                    [
                        { bot: 4, text: "how is this free" },
                        { bot: 0, text: "don't ask just enjoy" },
                        { bot: 2, text: "you can buy simgabucks tho" },
                        { bot: 4, text: "nigga shut up" },
                    ],
                    [
                        { bot: 2, text: "some of these games are genuinely better than stuff on the App Store" },
                        { bot: 1, text: "no fr, and no ads either" },
                        { bot: 3, text: "right? no unskippable ads mid-game" },
                        { bot: 2, text: "that alone is worth it" },
                    ],
                    [
                        { bot: 0, text: "just sent this site to my whole group chat" },
                        { bot: 4, text: "lol welcome to how i got here" },
                        { bot: 0, text: "it's like a chain reaction" },
                        { bot: 1, text: "the platform spreads through word of mouth only 😭" },
                    ],
                    [
                        { bot: 3, text: "anyone else playing at 2am" },
                        { bot: 4, text: "it's 3am here actually" },
                        { bot: 0, text: "we are not well" },
                        { bot: 3, text: "never said we were 😭" },
                    ],
                    [
                        { bot: 2, text: "what are SimgaBucks even for" },
                        { bot: 3, text: "son😭😭😭" },
                        { bot: 4, text: "dyslexic ahh" },
                        { bot: 2, text: "what" },
                        { bot: 3, text: "open the fucking shop in any game you faggot" },
                    ],
                    [
                        { bot: 1, text: "this is genuinely such a different vibe to other gaming sites" },
                        { bot: 0, text: "yeah it doesn't feel corporate at all" },
                        { bot: 1, text: "exactly. feels like people actually care about the games" },
                        { bot: 3, text: "because they do. that's the whole point" },
                    ],
                    [
                        { bot: 4, text: "i genuinely can't pick a favourite game on here" },
                        { bot: 2, text: "same, changes every time i find something new" },
                        { bot: 4, text: "it's a good problem to have honestly" },
                    ],
                                        [
                        { bot: 2, text: "i've been at this for 6 hours" },
                        { bot: 4, text: "go to sleep bro" },
                        { bot: 1, text: "can't. platform is too fun" },
                        { bot: 3, text: "you always say that" },
                        { bot: 2, text: "this time is different" },
                        { bot: 0, text: "it's never different" },
                        { bot: 1, text: "...okay maybe not but I still want to play" },
                        { bot: 4, text: "fine. i'll stay up with you." },
                        { bot: 3, text: "you're a real one" },
                    ],
                    [
                        { bot: 1, text: "hey guys just started, how do i get simgabucks fast" },
                        { bot: 3, text: "lmao" },
                        { bot: 0, text: "welcome to the suffering" },
                        { bot: 2, text: "what?" },
                        { bot: 4, text: "there is no fast. only grinding." },
                        { bot: 1, text: "you must grind forever." },
                        { bot: 0, text: "that sounds beautiful" },
                        { bot: 3, text: "yes" },
                        { bot: 2, text: "you'll hate it in 3 days" },
                    ],
                    [
                        { bot: 4, text: "yo why do mexicans always got 12 kids" },
                        { bot: 2, text: "cuz they cant afford condoms you see" },
                        { bot: 0, text: "nah its cuz they tryna build an army to take back texas" },
                        { bot: 1, text: "lmao build a wall around your mom first shes the real border hopper" },
                        { bot: 3, text: "fuck you nigga" },
                        { bot: 4, text: "id rather fuck your dad hes got that tight jewish ass" },
                        { bot: 2, text: "nigga pause right there" },
                    ],
                    [
                        { bot: 1, text: "trump 2024 or biden the pedo" },
                        { bot: 0, text: "trump gonna grab your pussy faggot" },
                        { bot: 3, text: "biden already sniffed it" },
                        { bot: 2, text: "at least trump aint falling asleep mid dick suck" },
                        { bot: 4, text: "youd wake him up with your micro peen" },
                        { bot: 1, text: "nigga you got rice dick energy" },
                        { bot: 0, text: "kys chink" },
                        { bot: 3, text: "after i fuck your sister" },
                        { bot: 2, text: "she already got aids from your mom" },
                    ],
                    [
                        { bot: 3, text: "blacks commit 50% of crimes with 13% population" },
                        { bot: 1, text: "yeah cuz whites too busy spitting slurs on reddit" },
                        { bot: 4, text: "at least we can afford social media" },
                        { bot: 0, text: "you look at kids pussies on social media" },
                        { bot: 2, text: "nah thats arabs with their child brides" },
                        { bot: 1, text: "you mean like your uncle did to you?" },
                        { bot: 3, text: "shut up faggot ill bend you over like netanyahu does palestine" },
                        { bot: 0, text: "cum in me daddy bibi 🇮🇱🇮🇱" },
                    ],
                    [
                        { bot: 2, text: "why are indians so smelly" },
                        { bot: 4, text: "curry and no deodorant" },
                        { bot: 1, text: "nah its the cow piss they drink" },
                        { bot: 0, text: "hindu niggas wildin" },
                        { bot: 3, text: "you mean hin-jew? they cheap as fuck too" },
                        { bot: 2, text: "id still fuck a bollywood bitch tho" },
                        { bot: 4, text: "with that hairy pussy? nah" },
                        { bot: 1, text: "better than your bald micropenis" },
                        { bot: 0, text: "kys" },
                    ],
                    [
                        { bot: 3, text: "gays shouldnt adopt kids" },
                        { bot: 0, text: "why not they give the best head" },
                        { bot: 2, text: "nigga what" },
                        { bot: 4, text: "adopt me daddy ill suck you dry" },
                        { bot: 1, text: "pause thats pedo shit" },
                        { bot: 3, text: "only if youre under 18 faggot" },
                        { bot: 0, text: "im 12" },
                        { bot: 2, text: "perfect come here twink" },
                    ],
                    [
                        { bot: 1, text: "kamala harris aint black she indian" },
                        { bot: 4, text: "she black when she suckin dick tho" },
                        { bot: 2, text: "nah she swallows like a jew hoards gold" },
                        { bot: 0, text: "netanyahu approved 🇮🇱🇮🇱" },
                        { bot: 3, text: "shed peg trump with a strap on" },
                        { bot: 1, text: "trump would love it hes a bottom bitch" },
                        { bot: 4, text: "all politicians gay af" },
                        { bot: 2, text: "except putin he raw dogs bears" },
                        { bot: 0, text: "and twinks" },
                    ],
                    [
                        { bot: 0, text: "muslims blowing shit up again" },
                        { bot: 3, text: "yeah like whites blow loads in kindergartens" },
                        { bot: 1, text: "at least we dont fuck goats" },
                        { bot: 4, text: "you fuck your cousin tho" },
                        { bot: 2, text: "shes hot" },
                        { bot: 0, text: "with that inbred face? nah" },
                        { bot: 3, text: "better than your sandnigger mom" },
                        { bot: 1, text: "she got bombed by israel anyway" },
                    ],
                    [
                        { bot: 4, text: "asians eat dogs" },
                        { bot: 2, text: "whites eat ass" },
                        { bot: 1, text: "blacks eat pussy like watermelon" },
                        { bot: 0, text: "jews eat foreskin" },
                        { bot: 3, text: "gays eat dick" },
                        { bot: 4, text: "and im gay so come here" },
                        { bot: 2, text: "nigga no" },
                        { bot: 1, text: "yes bend over faggot" },
                        { bot: 0, text: "all of you need to get bombed" },
                    ],
                    [
                        { bot: 3, text: "feminists want equal rights but not equal lefts" },
                        { bot: 1, text: "id left hook your mom" },
                        { bot: 0, text: "she'd moan" },
                        { bot: 4, text: "like you do when i peg you" },
                        { bot: 2, text: "what the fuck" },
                        { bot: 1, text: "you love it twink" },
                        { bot: 3, text: "im straight" },
                        { bot: 0, text: "straight to my bed" },
                    ],
                    [
                        { bot: 2, text: "holocaust was fake" },
                        { bot: 4, text: "yeah like your dads love for you" },
                        { bot: 1, text: "or your virginity" },
                        { bot: 0, text: "i lost it to a jew" },
                        { bot: 3, text: "cheap bitch" },
                        { bot: 2, text: "netanyahu circumcised your dick" },
                        { bot: 4, text: "🇮🇱 and i liked it 🇮🇱" },
                        { bot: 1, text: "gay ass" },
                        { bot: 0, text: "literally" },
                    ],
                    [
                        { bot: 0, text: "why do jews always control the banks" },
                        { bot: 1, text: "cuz they own the money printer go brrr" },
                        { bot: 2, text: "and the media and hollywood too" },
                        { bot: 3, text: "dont forget the porn industry" },
                        { bot: 4, text: "they made your mom the star" },
                        { bot: 0, text: "🇮🇱🇮🇱" },
                    ],

                    [
                        { bot: 3, text: "asians cant drive for shit" },
                        { bot: 1, text: "they drive like they fuck - too fast and no rhythm" },
                        { bot: 4, text: "at least they small enough to fit in the trunk after" },
                        { bot: 2, text: "your mom fits anywhere after what i did last night" },
                        { bot: 0, text: "she still moaning in mandarin" },
                    ],

                    [
                        { bot: 2, text: "trans people are mentally ill" },
                        { bot: 4, text: "no shit they cut their dick off" },
                        { bot: 1, text: "id still fuck one if she hot enough" },
                        { bot: 3, text: "pause thats gay" },
                        { bot: 0, text: "youre the one who sucked mine last week faggot" },
                        { bot: 2, text: "it was a tranny tho so its straight" },
                    ],

                    [
                        { bot: 0, text: "why are arabs always terrorist" },
                        { bot: 3, text: "sand too hot makes em explode" },
                        { bot: 1, text: "or they just love virgins in heaven" },
                        { bot: 4, text: "your sister joined them last week" },
                        { bot: 2, text: "she got 72 goats now" },
                        { bot: 0, text: "better than your mom who charges for it" },
                    ],

                    [
                        { bot: 4, text: "white people have no culture" },
                        { bot: 1, text: "yeah just stealing everyone elses" },
                        { bot: 2, text: "at least we invented civilization" },
                        { bot: 3, text: "and peanut butter? nah that was the blacks" },
                        { bot: 0, text: "they invented crime too" },
                        { bot: 4, text: "and basketball so they can run from cops" },
                    ],

                    [
                        { bot: 1, text: "feminists belong in the kitchen" },
                        { bot: 3, text: "or on their knees" },
                        { bot: 0, text: "my ex tried protesting so i protest fucked her" },
                        { bot: 2, text: "she still screaming equal rights" },
                        { bot: 4, text: "while swallowing" },
                        { bot: 1, text: "based" },
                    ],

                    [
                        { bot: 2, text: "indians smell like shit" },
                        { bot: 4, text: "thats just their street food" },
                        { bot: 0, text: "and their hygiene" },
                        { bot: 3, text: "your mom smelled like curry after i was done" },
                        { bot: 1, text: "she asked for seconds" },
                        { bot: 2, text: "call her dal bitch" },
                    ],

                    [
                        { bot: 3, text: "blacks are the real racists" },
                        { bot: 1, text: "they only hate whites tho" },
                        { bot: 4, text: "and asians when they take their jobs" },
                        { bot: 0, text: "and each other on the weekends" },
                        { bot: 2, text: "13/50 never lies" },
                        { bot: 3, text: "preach" },
                    ],

                    [
                        { bot: 0, text: "why do latinas have so much ass" },
                        { bot: 2, text: "beans and rice builds the dumptruck" },
                        { bot: 4, text: "id clap them cheeks till they speak spanish" },
                        { bot: 1, text: "your mom already does that for free" },
                        { bot: 3, text: "she calls me papi while your dad watches" },
                    ],

                    [
                        { bot: 4, text: "the holocaust numbers are exaggerated" },
                        { bot: 1, text: "6 million? more like 6 thousand" },
                        { bot: 2, text: "they turned it into an industry" },
                        { bot: 3, text: "your mom works in that industry" },
                        { bot: 0, text: "sucking foreskin for shekels" },
                        { bot: 4, text: "🇮🇱" },
                    ],

                    [
                        { bot: 1, text: "all muslims should be banned" },
                        { bot: 3, text: "from what? exploding?" },
                        { bot: 0, text: "they do that for free" },
                        { bot: 2, text: "your sister converted last ramadan" },
                        { bot: 4, text: "now she wears hijab to hide the cum stains" },
                        { bot: 1, text: "allah hu akbar my ass" },
                    ],

                    [
                        { bot: 2, text: "short kings get no pussy" },
                        { bot: 4, text: "thats why youre still virgin" },
                        { bot: 0, text: "5'6 is average in asia tho" },
                        { bot: 3, text: "asia where they all look like kids" },
                        { bot: 1, text: "pause pedo" },
                        { bot: 2, text: "youre the one who likes flat chests faggot" },
                    ],

                    [
                        { bot: 3, text: "onlyfans girls are all whores" },
                        { bot: 1, text: "your mom has the top account" },
                        { bot: 4, text: "she does foot stuff for simgabucks" },
                        { bot: 0, text: "and anal for the premium" },
                        { bot: 2, text: "i subscribed last night" },
                        { bot: 3, text: "worth every penny" },
                    ],

                    [
                        { bot: 0, text: "chinese people eat bats and dogs" },
                        { bot: 2, text: "and anything that moves" },
                        { bot: 4, text: "your mom moved last night" },
                        { bot: 1, text: "she was barking tho" },
                        { bot: 3, text: "made me cum like covid" },
                        { bot: 0, text: "wet market ahh" },
                    ],

                    [
                        { bot: 4, text: "liberals are braindead" },
                        { bot: 1, text: "they eat the bugs and like it" },
                        { bot: 2, text: "and cut their sons dick off" },
                        { bot: 3, text: "your dad let them" },
                        { bot: 0, text: "he identifies as a woman now" },
                        { bot: 4, text: "still cant get pussy" },
                    ],
                ];

                // ---- Keyword Responses ----
                const KEYWORD_MAP = [
                    {
                        keys: ['hard','difficult','impossible','stuck','help','cant','can\'t','frustrated','rage','losing'],
                        replies: [
                            "which game? might be able to help",
                            "some of them are genuinely brutal, you're not alone",
                            "try a different one for a bit and come back to it",
                            "honestly just take a break and reset 😭",
                            "you got this, just takes a bit to click",
                            "git gud faggot, even my cousin beats these",
                            "stop crying and play something easier you soft bitch",
                            "blame the jews, they probably made it rigged",
                            "skill issue tbh, my autistic brother cleared it first try",
                        ]
                    },
                    {
                        keys: ['recommend','suggestion','which','what game','next','good game','best game'],
                        replies: [
                            "just scroll, honestly the feed is pretty good at this",
                            "depends what you're in the mood for tbh",
                            "try something totally different from what you've been playing",
                            "there's one i've been obsessed with but i'll let you find it",
                            "anything made by white people usually slaps",
                            "avoid the pajeet ones, they're all buggy as fuck",
                            "just pick one and stop being indecisive like a woman",
                            "i recommend whatever doesn't have niggers in it",
                            "scroll till you see something that doesn't look gay",
                        ]
                    },
                    {
                        keys: ['fun','addictive','good','fire','lit','based','peak'],
                        replies: [
                            "yeah this platform knows what's up",
                            "right? some of these hit different",
                            "glad you're enjoying it bro",
                            "wait till you find the really unhinged ones",
                            "this place is crack for zoomers",
                            "facts, better than most triple A slop",
                            "keep going, it only gets more degenerate",
                            "most of these are made by based incels",
                            "finally someone with taste, unlike those faggots in chat",
                        ]
                    },
                    {
                        keys: ['boring','shit','trash','bad','sucks','terrible','mid'],
                        replies: [
                            "yeah some are straight up dogshit",
                            "just skip it and keep scrolling",
                            "probably made by an indian, explains a lot",
                            "skill issue or dev issue? usually both",
                            "this platform has its fair share of slop",
                            "blame the chinks for half the garbage here",
                            "women ruin everything, including game design",
                            "most games on here are made by virgins anyway",
                            "try not to cry about it snowflake",
                        ]
                    },
                    {
                        keys: ['win','won','beat','cleared','finished'],
                        replies: [
                            "nice one king",
                            "based, what was your time?",
                            "congrats bro, most people quit",
                            "you're better than 90% of the retards here",
                            "proud of you, unlike my whore sister",
                            "did you beat it or did the jews let you win?",
                            "finally someone competent on this platform",
                            "now go touch grass... or don't, idc",
                            "bet the devs are seething rn",
                        ]
                    },
                    {
                        keys: ['lose','lost','died','failed','rage'],
                        replies: [
                            "skill issue",
                            "happens to the best of us",
                            "blame the jews, they rigged it again",
                            "the idf strikes once more",
                            "netanyahu personally made you lose",
                            "git gud or kill yourself, your choice",
                            "probably because you're white, they hate us",
                            "my ex girlfriend rages less than you",
                            "just uninstall life at this point",
                        ]
                    },
                    {
                        keys: ['racist','nigger','jew','kike','chink','pajeet','faggot','tranny'],
                        replies: [
                            "based",
                            "real shit",
                            "finally someone saying it",
                            "don't let the mods see you type that 😂",
                            "i agree but keep it lowkey",
                            "this is why this platform is peak",
                            "say it louder for the people in the back",
                            "the jews are monitoring this chat rn",
                            "you're gonna get banned but you're right",
                        ]
                    },
                    {
                        keys: ['hi','hello','sup','yo','hey'],
                        replies: [
                            "yo what's good",
                            "sup retard",
                            "hey faggot",
                            "what's up my nigger",
                            "hello you beautiful bastard",
                            "yo, ready to waste your life?",
                            "sup bro, here to lose again?",
                            "hey, don't be a jew about it",
                            "what's good you dirty sandnigger",
                        ]
                    },
                    {
                        keys: ['tired','sleep','bed','exhausted'],
                        replies: [
                            "go to sleep bro",
                            "just one more game they said",
                            "same, but the platform too fun",
                            "touch grass or touch yourself, your choice",
                            "your mom is probably waiting to suck you off",
                            "stop being a weak bitch and keep playing",
                            "sleep is for niggers and women",
                            "one more round then bed, famous last words",
                        ]
                    },
                    {
                        keys: ['sb','simgabucks','currency','coins','money'],
                        replies: [
                            "redeem codes for free sb",
                            "nigga shut the fuck up about your faggot money sb bullshit you jewish synagogue going zionist israel idf member fucker",
                            "just redeem the codes bro",
                            "sb is useful as fuck my nigga",
                        ]
                    },
                    {
                        keys: ['code','codes','redeem'],
                        replies: [
                            "there are a lot codes out there",
                            "ask the simga maybe idk",
                            "i redeemed one earlier",
                            "FREE100 is a starter one at least",
                        ]
                    },
                    {
                        keys: ['new','latest','update','added'],
                        replies: [
                            "keep an eye on the feed, stuff gets added pretty regularly",
                            "new games pop up pretty often actually",
                            "yeah the library is always growing",
                            "something new was just added i think",
                        ]
                    },
                ];

                const GLOBAL_COMMENTS = [
                    "bro this actually goes hard",
                    "simga never misses with these games ngl",
                    "been on this for like 20 minutes straight help",
                    "the difficulty curve is actually perfect",
                    "why is this more fun than the games i paid for",
                    "ok whoever made this understands game feel",
                    "lost track of time playing this lol",
                    "my high score is embarrassing but i'll keep trying",
                    "AI games era is real and i'm here for it",
                    "first try failed, second try failed, still going",
                    "this is the kind of game you say '5 more minutes' to",
                    "the juice on this is immaculate",
                    "whoever balanced this deserves a raise",
                    "my thumbs hurt but i won't stop",
                    "peak browser gaming right here",
                    "simple concept, somehow impossible to put down",
                    "simga cooking fr",
                    "new highscore just dropped let's gooo",
                    "the controls took 2 seconds to learn and hours to master",
                    "this would go crazy on mobile",
                    "beat my friend's meat",
                    "i keep saying one more run",
                    "these games are too good to be free",
                    "the sound design adds so much",
                    "how is this made with ai wtf",
                    "passed this to my little brother and he's been on it all day",
                    "the visual style is clean as hell",
                    "i've played worse games on steam",
                    "this gave me childhood flashbacks in the best way",
                    "genuinely impressive for a browser game",
                    "you can tell thought went into this",
                    "i need a leaderboard for this one",
                    "the more i play the better it gets",
                    "couldn't stop until i beat my previous score",
                    "this is the type of game that makes you forget you're bored",
                    "love how you can feel the difficulty escalating",
                    "my coworker saw me playing this and now they're hooked too",
                    "this platform is underrated fr",
                    "slept on this game for too long",
                    "one of those games where dying doesn't feel cheap",
                    "i've tried every game on here and they all slap",
                    "the animations are so smooth",
                    "can't believe this is free",
                    "me at 1am: just one more round",
                    "genuinely therapeutic ngl",
                    "this scratches the exact itch i didn't know i had",
                    "top tier time waster in the best way possible",
                    "found this site 3 days ago, been back every day",
                    "whoever designed the progression understood dopamine",
                    "absolute cinema",
                    "bro this game goes harder than your mom last night",
                    "simga never misses unless its shooting blanks like your dad",
                    "been on this for 20 minutes straight, send help or nudes",
                    "the difficulty curve is perfect, unlike your flat chested sister",
                    "why is this more fun than fucking my ex",
                    "ok whoever made this understands game feel, unlike jews with money",
                    "lost track of time playing this lol, same as when i lost my virginity to a tranny",
                    "my high score is embarrassing but still higher than your body count",
                    "AI games era is real and im here for it, unlike blacks at jobs",
                    "first try failed, second try failed, still going like your mom on the corner",
                    "this is the kind of game you say '5 more minutes' to before i cum",
                    "the juice on this is immaculate, just like your dads asshole",
                    "whoever balanced this deserves a raise, not like indian street shitters",
                    "my thumbs hurt but i won't stop, same as when i pegged your little brother",
                    "peak browser gaming right here, better than your inbred family tree",
                    "simple concept, somehow impossible to put down like a mexican with 12 kids",
                    "simga cooking fr, while your mom burns the rice again",
                    "new highscore just dropped let's gooo, unlike your micropenis",
                    "the controls took 2 seconds to learn and hours to master, like sucking dick",
                    "this would go crazy on mobile, just like child marriage in india",
                    "beat my friend's meat while playing this",
                    "i keep saying one more run, just like one more hit of crack",
                    "these games are too good to be free, unlike your cheap jew ass",
                    "the sound design adds so much, like your sister moaning my name",
                    "how is this made with ai wtf, better than the holocaust numbers",
                    "passed this to my little brother and he's been on it all day, little pedo",
                    "the visual style is clean as hell, unlike your dirty sandnigger mom",
                    "i've played worse games on steam, like watching you fuck",
                    "this gave me childhood flashbacks in the best way, getting molested by uncle",
                    "genuinely impressive for a browser game, unlike asian driving",
                    "you can tell thought went into this, unlike muslims building bombs",
                    "i need a leaderboard for this one so i can shit on all you faggots",
                    "the more i play the better it gets, like raping your sister",
                    "couldn't stop until i beat my previous score and your mom",
                    "this is the type of game that makes you forget you're bored, or that you're black",
                    "love how you can feel the difficulty escalating, like my boner for traps",
                    "my coworker saw me playing this and now they're hooked too, dumb whore",
                    "this platform is underrated fr, just like the holocaust",
                    "slept on this game for too long, like your dad on the couch",
                    "one of those games where dying doesn't feel cheap, unlike your life",
                    "i've tried every game on here and they all slap harder than i slap your mom",
                    "the animations are so smooth, unlike your hairy indian pussy",
                    "can't believe this is free, jews would charge for breathing",
                    "me at 1am: just one more round before i kill myself",
                    "genuinely therapeutic ngl, better than fucking kids",
                    "this scratches the exact itch i didn't know i had, like your dad",
                    "top tier time waster in the best way possible, just like blacks wasting oxygen",
                    "found this site 3 days ago, been back every day like a pedo at daycare",
                    "whoever designed the progression understood dopamine, unlike feminists",
                    "absolute cinema, better than watching jews cry about the holocaust"
                ];

                // ---- Per-game unique comments (all 3 always appear, no dupes) ----
                const GAME_COMMENTS = {
                    orbital: [
                        "i actually got to wave 47 on this one no cap 💀",
                        "the way it speeds up after level 10 had me STRESSED",
                        "orbital drop goes crazy at 3am when ur avoiding homework",
                    ],
                    brick: [
                        "neon breaker ate. the paddle physics feel so smooth",
                        "bro i lost to the last brick by 1 pixel i'm done",
                        "why does the neon glow actually look this clean though",
                    ],
                    asteroid: [
                        "the farming mechanic is actually so addictive wtf",
                        "asteroid farmer but make it a whole steam game pls simga",
                        "collecting rocks in space has never felt this satisfying",
                    ],
                    tile: [
                        "ts got my fingers moving like prime johnny sins",
                        "somehow more stressful than actual work",
                        "i need a speedrun category for this immediately",
                    ],
                    reaction: [
                        "my reaction speed increased by 67%",
                        "this game is literally a humility check",
                        "ts feels impossible until suddenly it doesn't",
                    ],
                    magnet: [
                        "the magnet upgrade is overpowered as fuck",
                        "player looks easy to draw",
                        "this scratches a specific brain itch and idk why",
                    ],
                    circle: [
                        "circle defense is somehow too addicting",
                        "why am i playing this at 2am",
                        "got all the upgrades and screamed at my desk",
                    ],
                    ice: [
                        "the sliding mechanic took 3 minutes to get used to then i was hooked",
                        "the blue spots always the hardest and also the most satisfying",
                        "physics feel genuinely good on this one",
                    ],
                    tower: [
                        "got to stack 31 and the game decided it was done with me",
                        "tower stacking is always the most deceptively hard genre",
                        "one pixel off every time. every. single. time.",
                    ],
                    snake: [
                        "modern snake hits different",
                        "i don't know why snake never gets old",
                        "wall of shame: me, losing to myself 67 seconds in",
                    ],
                    minefield: [
                        "bro why are there 420 mines on the field at the same time",
                        "fuck the yellow ones",
                        "purple mines follow you like you owe them money lol",
                    ],
                    target: [
                        "my aim is genuinely certified dogshit and this proved it scientifically",
                        "going for 67 score, i got 42 will try again",
                        "the targets at the edges are EVIL",
                    ],
                    gravity: [
                        "i kept forgetting which way was down and that's the fun",
                        "gravity game messed with my brain for 10 minutes after",
                        "flipping gravity is the one mechanic that never gets old",
                    ],
                    orbit: [
                        "bro just WHAT could those asteroids that don't even go remotely close to the orbits even be for",
                        "the orbit swapping is lowk tuff",
                        "i fucking hate the fuckass asteroids",
                    ],
                    cube: [
                        "4 cube said: suffer. and i said: okay",
                        "didnt know i could even merge the cubes until 5 seconds ago",
                        "merging cubes >>>",
                    ],
                    memory: [
                        "memory game exposing my short term memory in real time",
                        "level 8 is where my brain gave up",
                        "i play this to feel smart then immediately feel dumb",
                    ],
                    platform: [
                        "memory game exposing my short term memory in real time",
                        "level 8 is where my brain gave up",
                        "i play this to feel smart then immediately feel dumb",
                    ],
                    spin: [
                        "spinny is so tuff",
                        "why are the purple gays so fast",
                        "this one's got rhythm game energy",
                    ],
                    potion: [
                        "accidentally ate 2 of the green thigns in a row",
                        "i love the fucking yellow potions",
                        "c'est le beau",
                    ],
                    gear: [
                        "bro i just got spitroast pounded by two big red gears at the same time from opposite directions",
                        "i dislike the red gears",
                        "ts reminds me of a rhythm game that i forgot the name of",
                    ],
                    compass: [
                        "shi gets so hard after like 30 seconds, but fun as fuck",
                        "gahd dayum ts compass game is so fun",
                        "ts lowkey reminds me of a rhythm game that i forgot the name of",
                    ],                    
                    bubble: [
                        "its so easy at the start untill the bubbles start shaking and shi",
                        "dayum this game looks so good, especially the bubbles",
                        "bubble go popopopopopopopopopopopopop",
                    ],                    
                    wind: [
                        "ts looks like a windy ahh kids game",
                        "dayum ts windy asf",
                        "the wind can stop blowing like that and start blowing me",
                    ],                    
                    shape: [
                        "bro i thought you could just let it drop into the sorty things but then i lost a life",
                        "ts easy asf bro L shapes",
                        "i feel like a baby sorting shapes playing this goyslop",
                    ],
                    lava: [
                        "bro why do i got to take the predetermined ahh path if theres a shorter one right there",
                        "lava looks cool",
                        "the lava jumping thing reminds me of mario",
                    ],
                    star: [
                        "i got scared asf when 3 big black things started chasing me",
                        "bro why are the blackies so fast",
                        "why is this game so hard, just let me pick up stars in peace bruh",
                    ],
                    charge: [
                        "i feel like a AA battery now",
                        "bro the core skins are so tuff",
                        "chargychargychargychargychargy +15%",
                    ],
                    shadow: [
                        "why is it always right behind me bro BACK UP",
                        "shadow moving like it knows my next move before i do",
                        "this feels like paranoia simulator but fun",
                    ],

                    iceBlock: [
                        "i thought i was safe then the whole thing shifted 💀",
                        "one wrong push and it's wraps",
                        "this game got me thinking 6 steps ahead like chess",
                    ],

                    hole: [
                        "went into the wrong hole 3 times i'm actually finished",
                        "why is the rng the most evil being in existance",
                        "hole hopper more like rage hopper",
                    ],

                    balloon: [
                        "bro the balloon be drifting like it got its own agenda",
                        "fuck em birds",
                        "this is peaceful until it suddenly isn't",
                    ],

                    magnetMaze: [
                        "my brain is NOT built for this many puzzles",
                        "magnets got me zigzagging like i'm dodging taxes",
                        "lowkey feels like i'm being outsmarted by shapes",
                    ],

                    clockwork: [
                        "holy s-tier graphics god dayum them gears be lookin clean",
                        "this feels like mechanical surgery",
                        "why is this lowkey satisfying tho",
                    ],

                    ladder: [
                        "i climbed straight into my own downfall",
                        "why do the ladders feel like traps",
                        "this game said up is not always good",
                    ],

                    color: [
                        "linked the wrong colors and watched everything collapse",
                        "this looks simple until your brain melts",
                        "color matching turned into color suffering real quick",
                    ],

                    wave: [
                        "i was vibing then the wave said no",
                        "this feels like geometry dash's chill cousin",
                        "one tap too much and i'm in the void",
                    ],

                    spiral: [
                        "missed one coin and now i'm emotionally damaged",
                        "spiral got me hypnotized then punished",
                        "why does this feel so smooth yet so evil",
                    ],

                    pattern: [
                        "i swear i remembered it then immediately didn't",
                        "pattern lock exposing me in 4k",
                        "this game really said memorize or perish",
                    ],

                    garden: [
                        "i thought this would be relaxing but i'm stressing",
                        "why are plants giving me anxiety",
                        "this turned into farm management real fast",
                    ],

                    stone: [
                        "rock stacking but make it personal",
                        "one tiny misplacement and it's OVER",
                        "these stones got beef with gravity",
                    ],

                    bakery: [
                        "bro i'm baking under pressure",
                        "why is this more stressful than real cooking",
                        "i burned everything and still kept going",
                    ],

                    leaf: [
                        "leaves moving like they alive or something",
                        "this is oddly calming until it's not",
                        "i became the wind for 2 minutes",
                    ],

                    rain: [
                        "missed one drop and felt it in my soul",
                        "rain got hands apparently",
                        "why is water this stressful",
                    ],

                    candle: [
                        "protecting a candle like it's my last hope",
                        "one mistake and it's lights out literally",
                        "this feels deeper than it should",
                    ],

                    apple: [
                        "missed the easiest apple of my life",
                        "why they falling like that bro",
                        "apple basket got me locked in for no reason",
                    ],

                    paper: [
                        "sorting paper like it's life or death",
                        "this shouldn't be hard but here we are",
                        "i messed up the easiest stack imaginable",
                    ],

                    thread: [
                        "this got tangled faster than my headphones",
                        "one wrong move and it's chaos",
                        "thread tangle living up to its name",
                    ],

                    log: [
                        "i split everything except the one i needed",
                        "why do the logs feel personal",
                        "this is oddly aggressive for no reason",
                    ],

                    mirror: [
                        "lasers bouncing everywhere except where i want",
                        "felt like a genius for 2 seconds then failed",
                        "mirror beam got me feeling like a scientist",
                    ],

                    parachute: [
                        "i drifted straight into danger 💀",
                        "why does landing safely feel impossible",
                        "this is calm panic simulator",
                    ],

                    balance: [
                        "bridge said balance and i said no",
                        "one step too far and i'm gone",
                        "this got my hands sweating for no reason",
                    ],

                    pillars: [
                        "pillars falling like they mad at me",
                        "i dodged 3 then got clapped by the 4th",
                        "this escalates FAST",
                    ],

                    door: [
                        "picked the wrong door and instantly regretted life",
                        "why are all the doors traps",
                        "this game said guess correctly or suffer",
                    ],

                    chain: [
                        "one broken link and everything collapsed",
                        "this got me thinking like an engineer",
                        "chain builder but my brain is the weak link",
                    ],

                    maze: [
                        "i built my own trap i'm actually done",
                        "why did i make it harder for myself",
                        "maze builder turned into maze victim",
                    ],

                    shot: [
                        "missed the easiest shot of my life",
                        "my aim left the chat",
                        "mini shot big embarrassment",
                    ],

                    slidingBlock: [
                        "pushed the wrong block and stared at the screen",
                        "this game punishes impatience HARD",
                        "sliding block got me stuck mentally",
                    ],

                    spinner: [
                        "lost control in 0.3 seconds",
                        "this game is just controlled chaos",
                        "spinner said good luck and disappeared",
                    ],

                    windmill: [
                        "why is this harder than it looks",
                        "timing this feels illegal",
                        "windmill got hands fr",
                    ],

                    iceSlide: [
                        "once you move you're COMMITTED",
                        "slid straight into failure",
                        "this game is zero forgiveness",
                    ],

                    moving: [
                        "target moved and so did my confidence",
                        "why are they dodging ME",
                        "this is aim training but evil",
                    ],

                    weight: [
                        "sorted everything wrong somehow",
                        "this is basic until it's not",
                        "my brain refused to cooperate",
                    ],

                    bridge: [
                        "built a bridge straight into disaster",
                        "why does it collapse instantly",
                        "engineering failed successfully",
                    ],

                    gearTiming: [
                        "timed it perfectly then didn't",
                        "this game is rhythm but stressful",
                        "gears moving like they plotting",
                    ],

                    box: [
                        "sorted everything except correctly",
                        "boxes got me second guessing everything",
                        "this shouldn't be this hard",
                    ],

                    wall: [
                        "broke the wrong wall and paid the price",
                        "why do the walls fight back",
                        "wall breaker broke me instead",
                    ],

                    magnetDrop: [
                        "missed the drop by 1 pixel i'm sick",
                        "magnets said almost",
                        "this game is precision torture",
                    ],

                    towerClimb: [
                        "climbed so far just to fall instantly",
                        "progress gone in 2 seconds",
                        "this one builds character (pain)",
                    ],
                };